# Generated by Django 4.2.7 on 2026-02-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_image_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='treading',
            field=models.BooleanField(default=False, help_text='0=default, 1=Trending'),
        ),
    ]
