# Generated by Django 4.2.7 on 2026-03-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_treading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='product_images',
        ),
    ]
